### ISSUE TITLE
AI neuronal alarm activated by default

### ISSUE THREAD

**Issue by pmithrandir** [OpenSeizureDetector/Android_Pebble_SD#170]
Hi @jones139 

I recall you told me that the AI alarm is not ready yet.

But it seems it's activated by default. Maybe we should disable it by default to prevent false alarm to lower the UX and make people unhappy.

Should be quite straightforward I bet...
https://github.com/OpenSeizureDetector/Android_Pebble_SD/blob/8f905b068f20ce643f92f4151df24da730cf6e88/app/src/main/res/xml/seizure_detector_prefs.xml#L10 turning default to false.

Pierre

**Comment by jones139** [comment]
Agreed - my main concern with it was that it was missing some seizures that the original OSD algorithm caught - I didn't have a false alarm issue with it, but there again it was trained against a lot of our false alarm data, so is biased towards our Benjamin!   Will be fixed in Release V4.2.x (6ca038b).

**Comment by jones139** [comment]
This should close automatically when we merge V4.2.x into the master branch....

**Comment by jones139** [comment]
Closing it manually to tidy up the to-do list!
