### ISSUE TITLE
Fall detection doesn't seem to work at all

### ISSUE THREAD

**Issue by ach80** [OpenSeizureDetector/Android_Pebble_SD#22]
I tried to provoke false alarm by dropping the watch with different settings and was unable to generate an alarm. Several people had falling accidents while using OSD and there was no alarm either.

**Comment by jones139** [comment]
I think you are right, it is not working - will add some debugging messages to the code to see what it is doing - I didn't think anyone used this feature so I never test it.

**Comment by jones139** [comment]
I think I have found the issue.   For fall detection to work you have to enable 'Latch Alarms' in the alarms menu.   This is because a fall is a one-off event so there is no second chance of spotting it.   This means that the alarm will sound continuously until you press the 'Accept Alarm' button on the main screen.
Also I am not sure about the settings.   The default upper threshold of 1200 mg is a bit low - most samples of data exceed that - maybe set it to 3000 so there has to be a noticeable 'thud'.    The lower threshold of 200 mg is quite an uncontrolled fall - could try increasing that a bit - but it will increase the number of false alarms.

If people are interested in this feature we should probably do a bit of research and use a better algorithm for fall detection.

**Comment by ach80** [comment]
Yes it is working with Latch Alarms enabled, thank you very much. I guess it would be worthwhile to make that more intuitive in the next version - latch alarms should be automatically enabled along with fall detection, or something like that.
It is a very looked after feature - I have contact with a couple of epileptic people who rarely suffer tonic-clonic seizures but often suffer attacks where they suddenly lose consciousness and fall down hurting themselves.

**Comment by jones139** [comment]
I have checked the code and setting a high minimum acceleration value (say 1500 mg), so the 'value<minimum' condition will always be met, and a maximum threshold of say 3500 mg would probably catch the fall that I have on record.   Have updated the default settings in V4.2.x so we can try that, and re-visit fall detection if necessary after some more testing.
